server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-feign-login
  thymeleaf:
    cache: false
    encoding: utf-8
    content-type: text/html
feign:
  hystrix:
    enabled: true
